### ISSUE TITLE
Issue with ConvertTo-PowerShell when there is <# and #>

### ISSUE THREAD

**Issue by MsSQLGirl** [dfinke/PowerShellNotebook#36]
Hello,

I tried converting a couple of PowerShell scripts from tigertoolbox this morning and found a few issues. The Notebook that I used to do the conversion is this: https://gist.githubusercontent.com/MsSQLGirl/b972d381fc85181aeafde5daa15ca171/raw/5d3db3ad14ef06304069bd74b53552b6879f15bf/PowerShellNotebook-ConversionIssue

```
Exception calling "Substring" with "2" argument(s): "Index and length must refer to a location within the string.
Parameter name: length"
At C:\Users\jukoesma\Documents\WindowsPowerShell\Modules\PowerShellNotebook\2.6.3\ConvertToPowerShellNoteBook.ps1:85 
char:28
+ ...  'Comment' {$TextBlock = $s.Substring($Block.Start, $Block.Length) -r ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException
 
```

I'm exhibiting this error whenever the source powershell file uses `<#` and `#>`

**Comment by dfinke** [comment]
@SQLvariant could you take a look. I don't remember where we left off on block comments for this. Also, I'll look at adding the ability for this to read from a URL so the `irm` step can be skipped.

**Comment by dfinke** [comment]
- Added features to `ConvertTo-PowerShellNotebook`
    - Pipe files to the function
    - Handles URLs with PowerShell files as endpoints
    - Handles any mix of Files and URLs for conversion
