### ISSUE TITLE
Any support for .NET Interactive notebooks?

### ISSUE THREAD

**Issue by TylerLeonhardt** [dfinke/PowerShellNotebook#4]
I notice that this was made to work with the PowerShell kernel that ships in Azure Data Studio. Do you know how well it works with the .NET Interactive kernel?

I'd love to be able to pull this in and use it there!

**Comment by dfinke** [comment]
I started working on parsing Jupyter Notebooks, in the branch AddJupyterNotebookMetaInfo. Wanted one module for both formats. Still in progress.
