### ISSUE TITLE
Export-NotebookToPowerShellScript does not Export Text as Block-comments

### ISSUE THREAD

**Issue by SQLvariant** [dfinke/PowerShellNotebook#47]
The Export-NotebookToPowerShellScript command does not export Text cells from a Jupyter Notebook as Block-comments to the PowerShell script it creates.

**Comment by dfinke** [comment]
`-IncludeTextCells` shoud add the block comments.

```powershell
Export-NotebookToPowerShellScript .\MultiLineSourceAsArray.ipynb -IncludeTextCells
```
